05/08/2020 10:53:36 AM : DEBUG : b''
05/08/2020 10:53:36 AM : INFO : Checking for ERROR/WARNING/FAILURE messages in system logs:['/var/log/syslog', '/var/log/messages', '/tmp/dmesg']
05/08/2020 10:53:36 AM : DEBUG : b"/var/log/messages:808:May  7 19:41:49 localhost python3.6[986]: 2020-05-07T11:41:49.085049Z INFO Daemon Error getting cloud-init enabled status from systemctl: Command '['systemctl', 'is-enabled', 'cloud-init-local.service']' returned non-zero exit status 1.\n/var/log/messages:812:May  7 19:41:49 localhost python3.6[986]: 2020-05-07T11:41:49.177781Z INFO Daemon Error getting cloud-init enabled status from service: Command '['service', 'cloud-init', 'status']' returned non-zero exit status 4.\n/var/log/messages:2561:May  6 00:08:26 localhost NetworkManager[2930]: <warn>  [1588694906.4903] dns-sd-resolved[dee3d138813c2cd9]: send-updates failed to update systemd-resolved: GDBus.Error:org.freedesktop.resolve1.NoSuchLink: Link 2 not known\n/var/log/messages:2563:May  6 00:08:26 localhost NetworkManager[2930]: <warn>  [1588694906.4903] dns-sd-resolved[dee3d138813c2cd9]: send-updates failed to update systemd-resolved: GDBus.Error:org.freedesktop.resolve1.NoSuchLink: Link 2 not known\n/var/log/messages:2564:May  6 00:08:26 localhost NetworkManager[2930]: <warn>  [1588694906.4903] dns-sd-resolved[dee3d138813c2cd9]: send-updates failed to update systemd-resolved: GDBus.Error:org.freedesktop.resolve1.NoSuchLink: Link 2 not known\n"
05/08/2020 10:53:36 AM : DEBUG : b'/var/log/messages:390:May  7 19:41:21 localhost kernel: random: 7 urandom warning(s) missed due to ratelimiting\n/var/log/messages:781:May  7 19:41:47 localhost kdumpctl[987]: Warning: There might not be enough space to save a vmcore.\n/var/log/messages:1086:May  7 19:42:04 localhost python3.6[986]: 2020-05-07T11:42:04.901311Z WARNING ExtHandler Dhcp client is not running.\n/var/log/messages:2561:May  6 00:08:26 localhost NetworkManager[2930]: <warn>  [1588694906.4903] dns-sd-resolved[dee3d138813c2cd9]: send-updates failed to update systemd-resolved: GDBus.Error:org.freedesktop.resolve1.NoSuchLink: Link 2 not known\n/var/log/messages:2562:May  6 00:06:10 localhost kdumpctl[1000]: Warning: There might not be enough space to save a vmcore.\n/var/log/messages:2563:May  6 00:08:26 localhost NetworkManager[2930]: <warn>  [1588694906.4903] dns-sd-resolved[dee3d138813c2cd9]: send-updates failed to update systemd-resolved: GDBus.Error:org.freedesktop.resolve1.NoSuchLink: Link 2 not known\n/var/log/messages:2564:May  6 00:08:26 localhost NetworkManager[2930]: <warn>  [1588694906.4903] dns-sd-resolved[dee3d138813c2cd9]: send-updates failed to update systemd-resolved: GDBus.Error:org.freedesktop.resolve1.NoSuchLink: Link 2 not known\n/var/log/messages:2566:May  5 22:33:25 localhost kdumpctl[984]: Warning: There might not be enough space to save a vmcore.\n/tmp/dmesg:453:[    4.300281] random: 7 urandom warning(s) missed due to ratelimiting\n'
05/08/2020 10:53:36 AM : DEBUG : b'/var/log/messages:201:May  7 19:41:20 localhost kernel: acpi PNP0A03:00: fail to add MMCONFIG information, can\'t access extended PCI configuration space under this bridge.\n/var/log/messages:371:May  7 19:41:20 localhost kernel: psmouse serio1: trackpoint: failed to get extended button data, assuming 3 buttons\n/var/log/messages:383:May  7 19:41:20 localhost rngd[367]: Failed to init entropy source hwrng\n/var/log/messages:596:May  7 19:41:44 localhost augenrules[786]: failure 1\n/var/log/messages:604:May  7 19:41:44 localhost augenrules[786]: failure 1\n/var/log/messages:612:May  7 19:41:44 localhost augenrules[786]: failure 1\n/var/log/messages:653:May  7 19:41:45 localhost rngd[898]: Failed to init entropy source hwrng\n/var/log/messages:1047:May  7 19:41:59 localhost dracut[1278]:    microcode_ctl: kernel version "4.18.0-193.2.1.el8_2.x86_64" failed early load check for "intel-06-2d-07", skipping\n/var/log/messages:1049:May  7 19:41:59 localhost dracut[1278]:    microcode_ctl: kernel version "4.18.0-193.2.1.el8_2.x86_64" failed early load check for "intel-06-4f-01", skipping\n/var/log/messages:1051:May  7 19:41:59 localhost dracut[1278]:    microcode_ctl: kernel version "4.18.0-193.2.1.el8_2.x86_64" failed early load check for "intel-06-55-04", skipping\n/var/log/messages:2561:May  6 00:08:26 localhost NetworkManager[2930]: <warn>  [1588694906.4903] dns-sd-resolved[dee3d138813c2cd9]: send-updates failed to update systemd-resolved: GDBus.Error:org.freedesktop.resolve1.NoSuchLink: Link 2 not known\n/var/log/messages:2563:May  6 00:08:26 localhost NetworkManager[2930]: <warn>  [1588694906.4903] dns-sd-resolved[dee3d138813c2cd9]: send-updates failed to update systemd-resolved: GDBus.Error:org.freedesktop.resolve1.NoSuchLink: Link 2 not known\n/var/log/messages:2564:May  6 00:08:26 localhost NetworkManager[2930]: <warn>  [1588694906.4903] dns-sd-resolved[dee3d138813c2cd9]: send-updates failed to update systemd-resolved: GDBus.Error:org.freedesktop.resolve1.NoSuchLink: Link 2 not known\n/var/log/messages:2565:May  6 00:16:11 localhost dnf[7457]: Failed determining last makecache time.\n/var/log/messages:2567:May  5 22:46:23 LISAv2-OneVM-walaautol2483-KI66-20200505073040-role-0 dnf[5291]: Failed determining last makecache time.\n/tmp/dmesg:253:[    0.645017] acpi PNP0A03:00: fail to add MMCONFIG information, can\'t access extended PCI configuration space under this bridge.\n/tmp/dmesg:443:[    2.647124] psmouse serio1: trackpoint: failed to get extended button data, assuming 3 buttons\n'
05/08/2020 10:53:36 AM : INFO : Checking ignorable boot ERROR/WARNING/FAILURE messages...
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:201:May  7 19:41:20 localhost kernel: acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:371:May  7 19:41:20 localhost kernel: psmouse serio1: trackpoint: failed to get extended button data, assuming 3 buttons
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:383:May  7 19:41:20 localhost rngd[367]: Failed to init entropy source hwrng
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:596:May  7 19:41:44 localhost augenrules[786]: failure 1
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:604:May  7 19:41:44 localhost augenrules[786]: failure 1
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:612:May  7 19:41:44 localhost augenrules[786]: failure 1
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:653:May  7 19:41:45 localhost rngd[898]: Failed to init entropy source hwrng
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:1047:May  7 19:41:59 localhost dracut[1278]:    microcode_ctl: kernel version "4.18.0-193.2.1.el8_2.x86_64" failed early load check for "intel-06-2d-07", skipping
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:1049:May  7 19:41:59 localhost dracut[1278]:    microcode_ctl: kernel version "4.18.0-193.2.1.el8_2.x86_64" failed early load check for "intel-06-4f-01", skipping
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:1051:May  7 19:41:59 localhost dracut[1278]:    microcode_ctl: kernel version "4.18.0-193.2.1.el8_2.x86_64" failed early load check for "intel-06-55-04", skipping
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:2561:May  6 00:08:26 localhost NetworkManager[2930]: <warn>  [1588694906.4903] dns-sd-resolved[dee3d138813c2cd9]: send-updates failed to update systemd-resolved: GDBus.Error:org.freedesktop.resolve1.NoSuchLink: Link 2 not known
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:2563:May  6 00:08:26 localhost NetworkManager[2930]: <warn>  [1588694906.4903] dns-sd-resolved[dee3d138813c2cd9]: send-updates failed to update systemd-resolved: GDBus.Error:org.freedesktop.resolve1.NoSuchLink: Link 2 not known
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:2564:May  6 00:08:26 localhost NetworkManager[2930]: <warn>  [1588694906.4903] dns-sd-resolved[dee3d138813c2cd9]: send-updates failed to update systemd-resolved: GDBus.Error:org.freedesktop.resolve1.NoSuchLink: Link 2 not known
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:2565:May  6 00:16:11 localhost dnf[7457]: Failed determining last makecache time.
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:2567:May  5 22:46:23 LISAv2-OneVM-walaautol2483-KI66-20200505073040-role-0 dnf[5291]: Failed determining last makecache time.
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /tmp/dmesg:253:[    0.645017] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /tmp/dmesg:443:[    2.647124] psmouse serio1: trackpoint: failed to get extended button data, assuming 3 buttons
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:2561:May  6 00:08:26 localhost NetworkManager[2930]: <warn>  [1588694906.4903] dns-sd-resolved[dee3d138813c2cd9]: send-updates failed to update systemd-resolved: GDBus.Error:org.freedesktop.resolve1.NoSuchLink: Link 2 not known
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:2563:May  6 00:08:26 localhost NetworkManager[2930]: <warn>  [1588694906.4903] dns-sd-resolved[dee3d138813c2cd9]: send-updates failed to update systemd-resolved: GDBus.Error:org.freedesktop.resolve1.NoSuchLink: Link 2 not known
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:2564:May  6 00:08:26 localhost NetworkManager[2930]: <warn>  [1588694906.4903] dns-sd-resolved[dee3d138813c2cd9]: send-updates failed to update systemd-resolved: GDBus.Error:org.freedesktop.resolve1.NoSuchLink: Link 2 not known
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:390:May  7 19:41:21 localhost kernel: random: 7 urandom warning(s) missed due to ratelimiting
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:781:May  7 19:41:47 localhost kdumpctl[987]: Warning: There might not be enough space to save a vmcore.
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:1086:May  7 19:42:04 localhost python3.6[986]: 2020-05-07T11:42:04.901311Z WARNING ExtHandler Dhcp client is not running.
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:2561:May  6 00:08:26 localhost NetworkManager[2930]: <warn>  [1588694906.4903] dns-sd-resolved[dee3d138813c2cd9]: send-updates failed to update systemd-resolved: GDBus.Error:org.freedesktop.resolve1.NoSuchLink: Link 2 not known
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:2562:May  6 00:06:10 localhost kdumpctl[1000]: Warning: There might not be enough space to save a vmcore.
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:2563:May  6 00:08:26 localhost NetworkManager[2930]: <warn>  [1588694906.4903] dns-sd-resolved[dee3d138813c2cd9]: send-updates failed to update systemd-resolved: GDBus.Error:org.freedesktop.resolve1.NoSuchLink: Link 2 not known
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:2564:May  6 00:08:26 localhost NetworkManager[2930]: <warn>  [1588694906.4903] dns-sd-resolved[dee3d138813c2cd9]: send-updates failed to update systemd-resolved: GDBus.Error:org.freedesktop.resolve1.NoSuchLink: Link 2 not known
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:2566:May  5 22:33:25 localhost kdumpctl[984]: Warning: There might not be enough space to save a vmcore.
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /tmp/dmesg:453:[    4.300281] random: 7 urandom warning(s) missed due to ratelimiting
05/08/2020 10:53:36 AM : INFO : Checking ignorable wala ERROR/WARNING/FAILURE messages...
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:808:May  7 19:41:49 localhost python3.6[986]: 2020-05-07T11:41:49.085049Z INFO Daemon Error getting cloud-init enabled status from systemctl: Command '['systemctl', 'is-enabled', 'cloud-init-local.service']' returned non-zero exit status 1.
05/08/2020 10:53:36 AM : INFO : Ignorable ERROR/WARNING/FAILURE message: /var/log/messages:812:May  7 19:41:49 localhost python3.6[986]: 2020-05-07T11:41:49.177781Z INFO Daemon Error getting cloud-init enabled status from service: Command '['service', 'cloud-init', 'status']' returned non-zero exit status 4.
